version: '3'
services:
  frontend:
    build:
      context: ./pftracker
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./pftrackerback
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:  # Define the network so that both services can communicate
    driver: bridge