version: '3'
services:
  frontend:
    build:
      context: ./pftracker
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USER_URL=http://user-service:8080
      - REACT_APP_TRANSACTION_URL=http://transaction-service:8081
    depends_on:
      - user-service
      - transaction-service
    networks:
      - app-network

  user-service:
    build:
      context: ./backServices/user-service
    ports:
      - "8080:8080"
    networks:
      - app-network


  transaction-service:
    build:
      context: ./backServices/transaction-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # This is where data is stored persistently`
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:  # Define the network so that both services can communicate
    driver: bridge
