version: '3'
services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USER_SERVICE_URL=http://user-service:8081
      - REACT_APP_TRANSACTION_SERVICE_URL=http://transaction-service:8082
    depends_on:
      - user-service
      - transaction-service
    networks:
      - app-network

  # User Service
  user-service:
    build:
      context: ./backServices/user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userdb
    depends_on:
      - mongodb
    networks:
      - app-network

  # Transaction Service
  transaction-service:
    build:
      context: ./backServices/transaction-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/transactiondb
    depends_on:
      - mongodb
    networks:
      - app-network

  # MongoDB Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:  # Shared network for all services
    driver: bridge