version: '3'
services:
  frontend:
    build:
      context: ./pftracker
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USER_URL=http://user-service:8080
      - REACT_APP_TRANSACTION_URL=http://transaction-service:8081
      - REACT_APP_BANK_MAPPING_URL=http://bank-mapping-service:5000  # URL for the Python service
    depends_on:
      - user-service
      - transaction-service
      - bank-mapping-service  # Add dependency for bank-mapping service
    networks:
      - app-network

  user-service:
    build:
      context: ./backServices/user-service
    ports:
      - "8080:8080"
    networks:
      - app-network

  transaction-service:
    build:
      context: ./backServices/transaction-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  bank-mapping-service:
    build:
      context: ./backServices/bank-mapping-service  # Adjust the path based on where your bank-mapping service is
    ports:
      - "5000:5000"  # Expose port 5000 for the Python Flask service
    networks:
      - app-network

  budget-service:
    build:
      context: ./backServices/budget-service
    ports:
      - "8082:8082"
    networks:
      - app-network


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local


networks:
  app-network:
    driver: bridge